version: "3"

vars:
  BINARY: openclaw-cortex
  GOFLAGS: -ldflags="-s -w"

tasks:
  ## Build

  build:
    desc: Build the openclaw-cortex binary
    cmds:
      - go build {{.GOFLAGS}} -o bin/{{.BINARY}} ./cmd/openclaw-cortex

  install:
    desc: Install openclaw-cortex to GOPATH/bin
    cmds:
      - go install {{.GOFLAGS}} ./cmd/openclaw-cortex

  ## Test

  test:
    desc: Run all tests with race detection
    cmds:
      - go test -v -race -count=1 ./...

  test:short:
    desc: Run short tests only
    cmds:
      - go test -short -count=1 ./...

  test:cover:
    desc: Run tests with coverage report
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  ## Lint

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  fmt:
    desc: Format code
    cmds:
      - gofmt -w .
      - goimports -w .

  ## Docker

  docker:up:
    desc: Start Qdrant via docker compose
    cmds:
      - docker compose up -d

  docker:down:
    desc: Stop Qdrant
    cmds:
      - docker compose down

  docker:build:
    desc: Build openclaw-cortex Docker image
    cmds:
      - docker build -t openclaw-cortex:latest .

  ## Cortex commands (requires Qdrant running)

  index:
    desc: Run openclaw-cortex index command
    cmds:
      - go run ./cmd/openclaw-cortex index {{.CLI_ARGS}}

  search:
    desc: Run openclaw-cortex search command
    cmds:
      - go run ./cmd/openclaw-cortex search {{.CLI_ARGS}}

  recall:
    desc: Run openclaw-cortex recall command
    cmds:
      - go run ./cmd/openclaw-cortex recall {{.CLI_ARGS}}

  capture:
    desc: Run openclaw-cortex capture command
    cmds:
      - go run ./cmd/openclaw-cortex capture {{.CLI_ARGS}}

  stats:
    desc: Show memory stats
    cmds:
      - go run ./cmd/openclaw-cortex stats

  consolidate:
    desc: Run lifecycle management
    cmds:
      - go run ./cmd/openclaw-cortex consolidate {{.CLI_ARGS}}

  ## Cleanup

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf bin/ coverage.out coverage.html

  ## Default

  default:
    desc: Show available tasks
    cmds:
      - task --list
